---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: ora-data193-snap
  namespace: oracle-namespace
spec:
  snapshotClassName: pure-snapshotclass
  source:
    name: ora-data193
    kind: PersistentVolumeClaim
